apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-mmontes
  namespace: media
spec:
  dependsOn:
    - name: mariadb-mmontes
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./apps/photoprism-mmontes
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-xiaowen
  namespace: media
spec:
  dependsOn:
    - name: mariadb-xiaowen
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./apps/photoprism-xiaowen
  prune: true
  timeout: 5m