apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mariadb-mmontes
  namespace: media
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./infrastructure/mariadb-mmontes
  prune: true
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: mariadb-xiaowen
#   namespace: media
# spec:
#   interval: 5m
#   sourceRef:
#     kind: GitRepository
#     name: flux-tenant-media
#     namespace: flux-system
#   path: ./infrastructure/mariadb-xiaowen
#   prune: true
#   timeout: 5m
