apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mariadb-mmontes
  namespace: media
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./infrastructure/mariadb-mmontes-v2
  prune: true
  timeout: 5m