---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-mmontes
  namespace: media
spec:
  encryptedData:
    password: AgCG5EgE9o5WracnV2bxUGeA3SFeoBSmYZ0/wnmIIzTYXOj+CgpDGvvX4J9rwu8BRq0tJWEhxutp356dHELxhsvVzRgE3h0sYuBGtL/RqrT9ARFYk+4wL0Qqe0/wQLQNwWPs34E7LeF3y/t2H6ocbv1PcclUi75MX4Vb35XK/jd22oStF+DpWgX28wRU30vLAscO1gPmFUwqe+431lKJuMIJfLqWKDy1+Ug5hJ3npVJLSVlqZ0QAxlGfmT+YYixD27um/fSaLWdBrbGKr5y76nFNgIfU5PktG0cUevUsUPk7L2KfTjllhC/vJcHqXTRGl8cX+OLNh3CYeevtzo6Fj8+bxcMrfCRLkSzoiw3B07g2gfkUJnA5tQtfsir6xYCbuhk2XEeTCyCMMhD7Mze60tCOuTTjAdkvGLaNArmMBJnGW5PjYtSzO8m5q606eR0vhoQzLuuOfShmRuHKzkrwGYO2uqpOGoDcimSgevA9H/oo/V6dXWwOMC1grpxGt24D1EF8Joe2BqUhvnFnq6gedNWFSj4Owali06lgNvDH4JGrR/OvU3iIluuqwlbBb4WaNs2FhTJpbhwxTdttV0R4tVt8873h5eeBSvXu+9yWUIACERL0krcpFyJ1tXIVbecYH2rBuY4DNP67tIeV1Xye1g0hgqPfnA5sp9EmLz9RRZeeauHcxK6swqnmpvvUn4w7GjRD3YqjJLowl2G4XLo2gyKShMuACw==
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-mmontes
      namespace: media
