apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-mmontes-mariadb
spec:
  releaseName: photoprism-mmontes-mariadb
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.2.0"
  interval: 5m
  values:
    image:
      repository: mariadb
      tag: "10.7.3"
      pullPolicy: IfNotPresent

    storage:
      size: 4Gi
      className: local-path
      accessModes:
        - "ReadWriteOnce"

    secretRef:
      name: photoprism-mmontes-mariadb

    resources:
      requests:
        cpu: 300m
        memory: 500Mi
      limits:
        cpu: 300m
        memory: 500Mi
