apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-xiaowen
spec:
  mariaDbRef:
    name: mariadb-xiaowen

  replicas: 2

  config:
    volumeClaimTemplate:
      storageClassName: topolvm
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: true
    adminUsername: xiaowen
    adminPasswordSecretKeyRef:
      name: mariadb-xiaowen
      key: password

  tls:
    enabled: false

  metrics:
    enabled: true

  suspend: false

  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 300m
      memory: 64Mi
    limits:
      memory: 128Mi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  nodeSelector:
    node.mmontes.io/type: compute-large