apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-xiaowen-snap
spec:
  mariaDbRef:
    name: mariadb-xiaowen
  schedule:
    cron: "30 3 * * *"
    suspend: false
    immediate: true
  maxRetention: 72h # 3 days
  storage:
    volumeSnapshot:
      volumeSnapshotClassName: topolvm
  timeout: 1h