---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-xiaowen
  namespace: media
spec:
  encryptedData:
    PHOTOPRISM_ADMIN_PASSWORD: AgABRkMrH/t1jx97LfUxBDZKeR6di1f988AFmJCIm/zcotBxD2hIjDP6Y21TZBoiBwpQRyfMBbg2DUZdlXseogkMaQmbDGLKK0AJacUPMMZacq9MksBNFAuV75eJnPH5Jxlnuud8DDnve9CupdokTMaiD+oPGfxI0ZU7jy0ugE0u3oP+iejbP52H5H5evmIaXQ1nMeY/PGG+3TChRF0zW/aq3LDfcRpTc4YPsjxT1YxD0frvfc2w2Smgf40Bs/06YP/WdU38DWMEzti9HzsWrMyoXyhW8RJblfqHn7OuywtlHC/HDmG5cL5LYmew7aS7Np3zPHLlXSYb4sBdJl+5x2VHKVun4BOtmPywex6CnTiKoNwc0yflcaYtwWI2I74Bs+/taxy8k/ckhs3I5lB1sLNT4J2Wsw4qr5FHsIW5nYWY4zwLJ4vy2TvzjcfzqCK5Ik5Du7E/0l/BZqs7psOz9UDW4ALgOsDzGW+AzrZQMrUvcSNdgyq83Kzk/vbnxNDxJ8iBgEohkcJhawo0ljh+XdkleuT5ugNhqqY/qXjwo8SVqlq5rVT8AjbDTGkTdmzj/pr/aQyi3S6aR3G1U//UgwMSdxhVNDwOpIK0+RwZrJVFnOIOgnPH/lGg67cK4yJuUy3/ZcbVBkPxsVv/RNQtIHbMjEWQNt0l3g64IDTWpJFaT0YD4nddBsocN4Y9ou9Gjr3QFyiCAwK0lXwDzGlD0VmQ5A==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-xiaowen
      namespace: media
