apiVersion: k8s.mariadb.com/v1alpha1
kind: Connection
metadata:
  name: connection-xiaowen
spec:
  mariaDbRef:
    name: mariadb-xiaowen
  username: xiaowen
  passwordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
  database: photoprism
  host: mariadb-xiaowen-primary.media.svc.cluster.local 
  secretName: connection-xiaowen
  secretTemplate:
    key: dsn
  params:
    parseTime: "true"
    tls: "false"