apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-xiaowen
spec:
  releaseName: photoprism-xiaowen
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.5.0"
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: photoprism-xiaowen
