apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: photoprism-xiaowen
spec:
  sourcePVC: photoprism-xiaowen
  trigger:
    manual: xiaowen-1
  restic:
    repository: restic-xiaowen
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: xiaowen-1
    copyMethod: Direct
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    moverAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.mmontes.io/type
                  operator: In
                  values:
                    - compute
    cacheCapacity: 10Gi
    cacheStorageClassName: rook-ceph
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle-v2
      key: ca.crt
