---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-xiaowen
  namespace: media
spec:
  encryptedData:
    password: AgCV00KVWtrcOk1TUH7sKcITACsgbavk1e7epRmj9A+s/Mw1jJmZpCxzgACjrKvrwOci+74LNaSJg8bi84JCUq5Eb4+saRUZJEu3alSEWSlCOpnDY4PkcwVBbG1AZUJRVj+ZtWzKhix2uoD9SFvUTVttl56f85SerqitlnaMfydbc3ZBmScUyTc2xAEvpEC/8UC2QCIvz+GCeziL6sVpGvm1qVXktNcfUhmbTKVblcN3xicxYjKq4DsbpGZqZ0+9dSLaY63wXd1NwUmGPNgecKLmq7aquttOX8R7uHmoWQBuHBBMC3BGX+1YAgunhkjcCYZxizHr4qffyIxH/UV/T7JdxtWNHrWJhxtczqG5YyzfX67n53GUfWs3N8Y5/KoFb9WIqZ5J5wGiq+oEK5FEPjxcP3mo0IxolN1zxG4E8DMggT+x1KGt0QBZ/pD5r4yI4+OW6FOok9Anl9NGreD3T7eAuXDNNx8qTwQ8yswkuDDANVzbTceb6XC86clbnhWSI2+7Z4WqgM7OG00sgw+m4CPwgMxIg/A4kMwIl+BpR1VMtdPxKcXS63wZWvzYow0UUdhTNhLj1Zul0hMOVx4d3niut2Z9CT8rl7Sn/wofxKaWPyTHuxze/LpzOZNgRQAkCsDXz7hiWdplhS1tCSCgkzoFIelTPrbngYmy8z2+76yfWp36X74HozKuG96o4boeD0MQghUlpMZxB8RSZ/U5d3KFYw==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-xiaowen
      namespace: media
