apiVersion: batch/v1
kind: CronJob
metadata:
  name: photoprism-xiaowen-storage-sync
spec:
  schedule: "0 1 * * *"
  suspend: false
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 5
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - name: storage-sync 
            image: ghcr.io/mmontes11/rsync:v0.1.0
            imagePullPolicy: IfNotPresent
            args:
              - -rlthv
              - --progress
              - /source
              - /destination
            resources:
              requests:
                cpu: 300m
                memory: 500Mi
              limits:
                memory: 1Gi
            volumeMounts:
            - mountPath: /source
              name: source
            - mountPath: /destination
              name: destination
          restartPolicy: OnFailure
          volumes:
          - name: source 
            persistentVolumeClaim:
              claimName: photoprism-xiaowen
          - name: destination
            nfs:
              path: /volume1/photoprism/xiaowen/storage
              server: 10.0.0.50
