apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-xiaowen
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 160Gi
  storageClassName: rook-ceph-fs
