image:
  repository: photoprism/photoprism
  tag: "221118-jammy"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "mmontes"
  PHOTOPRISM_SITE_CAPTION: "Champi"
  PHOTOPRISM_SITE_DESCRIPTION: "Champi"

secretRef:
  name: photoprism-xiaowen

persistence:
  enabled: true

  nas: &nas nas.local
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/xiaowen
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/import
    - name: storage
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  host: photoprism-xiaowen-mariadb:3306

sync:
  enabled: true
  cron: "0 4,16 * * *"
  resources:
    requests:
      memory: 300Mi
      cpu: 300m
    limits:
      memory: 1.7Gi
      cpu: 700m

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  host: xiaomedia.mmontes.duckdns.org
  gatewayRef:
    name: traefik
    namespace: networking

resources:
  requests:
    memory: 300Mi
    cpu: 300m
  limits:
    memory: 1.7Gi
    cpu: 700m
