image:
  repository: photoprism/photoprism
  tag: "250426"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_ADMIN_USER: xiaowen
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "Xiaowen"
  PHOTOPRISM_SITE_CAPTION: "Champi"
  PHOTOPRISM_SITE_DESCRIPTION: "Champi"
  PHOTOPRISM_BACKUP_DATABASE: false
  PHOTOPRISM_INDEX_SCHEDULE: ""
  PHOTOPRISM_INIT: "tensorflow"

secretRef:
  name: photoprism-xiaowen

persistence:
  enabled: true

  nas: &nas 10.0.0.50

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/xiaowen
        readOnly: true
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/import
        readOnly: true
    - name: storage
      persistentVolumeClaim:
        claimName: photoprism-xiaowen

  volumeMounts:
    - name: originals
      mountPath: /photoprism/originals
      readOnly: true
    - name: import
      mountPath: /photoprism/import
      readOnly: true
    - name: storage
      mountPath: /photoprism/storage

database:
  driver: mysql
  dsnSecretKeyRef:
    name: connection-xiaowen
    key: dsn

sync:
  enabled: true
  cron: "0 */3 * * *"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      memory: 4Gi

videoTranscoding:
  enabled: false

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  host: xiaomedia.mmontes-internal.duckdns.org
  gatewayRef:
    name: traefik-internal
    namespace: networking

resources:
  requests:
    cpu: 1
    memory: 2Gi
  limits:
    memory: 4Gi

nodeSelector:
  node.mmontes.io/type: compute