image:
  repository: photoprism/photoprism
  tag: "230514"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "mmontes"
  PHOTOPRISM_SITE_CAPTION: "Champi"
  PHOTOPRISM_SITE_DESCRIPTION: "Champi"

secretRef:
  name: photoprism-xiaowen

persistence:
  enabled: true

  nas: &nas nas.local
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/xiaowen
        readOnly: true
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/import
    - name: storage
      nfs:
        server: *nas
        path: /volume1/photoprism/xiaowen/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
      readOnly: true
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  dsnSecretKeyRef:
    name: photoprism-xiaowen-dsn
    key: dsn

sync:
  enabled: true
  cron: "0 4,16 * * *"
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 1.7Gi

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  host: xiaomedia.internal.mmontes.duckdns.org
  gatewayRef:
    name: traefik-internal
    namespace: networking

resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    memory: 1.7Gi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
