apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-mmontes-mariadb
  namespace: media
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./infrastructure/photoprism-mmontes-mariadb
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: photoprism-xiaowen-mariadb
  namespace: media
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-media
    namespace: flux-system
  path: ./infrastructure/photoprism-xiaowen-mariadb
  prune: true
  timeout: 5m
