apiVersion: k8s.mariadb.com/v1alpha1
kind: Connection
metadata:
  name: connection-mmontes
spec:
  mariaDbRef:
    name: mariadb-mmontes
  username: mmontes
  passwordSecretKeyRef:
    name: mariadb-mmontes
    key: password
  database: photoprism
  secretName: connection-mmontes
  secretTemplate:
    key: dsn
  params:
    parseTime: "true"
    tls: "false"