apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - connection.yaml
  - helmrelease.yaml
  - restic-sealedsecret.yaml
  - sealedsecret.yaml
  - storage-pvc.yaml