apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: photoprism-mmontes
spec:
  trigger:
    manual: mmontes-1
  restic:
    repository: restic-mmontes
    destinationPVC: photoprism-mmontes
    copyMethod: Direct
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
