apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup-mmontes
spec:
  mariaDbRef:
    name: mariadb-mmontes
  schedule:
    cron: "0 22 * * *"
    suspend: false
  maxRetention: 168h # 7 days
  compression: gzip
  storage:
    s3:
      bucket: database
      prefix: mariadb-mmontes/logical
      endpoint: minio.storage.svc.cluster.local:443
      accessKeyIdSecretKeyRef:
        name: mariadb-mmontes
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-mmontes
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: homelab-bundle
          key: ca.crt
  logLevel: info
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2