apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-mmontes
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-mmontes
    key: password
    generate: false

  username: mmontes
  passwordSecretKeyRef:
    name: mariadb-mmontes
    key: password
  database: photoprism

  image: mariadb:11.8.2

  # bootstrapFrom:
  #   backupContentType: Physical
  #   s3:
  #     bucket: database
  #     prefix: mariadb-mmontes/physical
  #     endpoint: minio.storage.svc.cluster.local:443
  #     accessKeyIdSecretKeyRef:
  #       name: mariadb-mmontes
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: mariadb-mmontes
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: homelab-bundle
  #         key: ca.crt

  # bootstrapFrom:
  #   volumeSnapshotRef:
  #     name: physicalbackup-mmontes-snap-20250918233000  

  storage:
    size: 4Gi
    storageClassName: topolvm

  tls:
    enabled: true
    required: false

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  suspend: false

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1600MB
    slow_query_log
    slow_query_log_file=mariadb-slow.log

  livenessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  startupProbe:
    failureThreshold: 30
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  nodeSelector:
    node.mmontes.io/type: compute-large