apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-mmontes
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-mmontes
    key: password
    generate: false

  username: mmontes
  passwordSecretKeyRef:
    name: mariadb-mmontes
    key: password
  database: photoprism

  image: mariadb:10.11.8

  storage:
    size: 4Gi

  metrics:
    enabled: true

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: 300m
      memory: 1024Mi
    limits:
      memory: 1024Mi

  nodeSelector:
    node.mmontes.io/type: compute   

  connection:
    secretName: connection-mmontes
    secretTemplate:
      key: dsn
    params:
      parseTime: "true"