apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-mmontes
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-mmontes
    key: password
    generate: false

  username: mmontes
  passwordSecretKeyRef:
    name: mariadb-mmontes
    key: password
  database: photoprism

  image: mariadb:11.4.4

  # bootstrapFrom:
  #   volume:
  #     nfs:
  #       server: 10.0.0.50
  #       path: /volume1/photoprism/mmontes/backup
  #   restoreJob:
  #     args:
  #       - "--verbose"
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         memory: 1Gi

  storage:
    size: 4Gi
    storageClassName: rook-ceph

  tls:
    enabled: true
    required: false

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast

  suspend: false

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=800MB
    max_allowed_packet=300M

  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi

  nodeSelector:
    node.mmontes.io/type: compute