apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-mmontes-snap
spec:
  mariaDbRef:
    name: mariadb-mmontes
  schedule:
    cron: "30 7 * * *"
    suspend: false
    immediate: true
  maxRetention: 720h # 30 days
  storage:
    volumeSnapshot:
      volumeSnapshotClassName: rook-ceph
  timeout: 1h