apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-mmontes-snap
spec:
  mariaDbRef:
    name: mariadb-mmontes
  schedule:
    cron: "30 23 * * *"
    suspend: false
    immediate: true
  maxRetention: 72h # 3 days
  storage:
    volumeSnapshot:
      volumeSnapshotClassName: rook-ceph
  timeout: 1h