apiVersion: k8s.mariadb.com/v1alpha1
kind: PointInTimeRecovery
metadata:
  name: pitr-mmontes
spec:
  physicalBackupRef:
    name: physicalbackup-mmontes
  storage:
    s3:
      bucket: database
      prefix: mariadb-mmontes/binlogs
      endpoint: seaweedfs-s3.storage.svc.cluster.local:8333
      accessKeyIdSecretKeyRef:
        name: mariadb-mmontes
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-mmontes
        key: secret-access-key
  compression: gzip
  archiveTimeout: 1h
  strictMode: true