apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-xiaowen
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
    generate: false

  username: xiaowen
  passwordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
  database: photoprism

  image: mariadb:11.8.5

  replicas: 2

  replication:
    enabled: true
    replica:
      replPasswordSecretKeyRef:
        name: mariadb-xiaowen
        key: password
      bootstrapFrom:
        physicalBackupTemplateRef:
          name: pb-xiaowen-tpl
      recovery:
        enabled: true
        errorDurationThreshold: 5m

  pointInTimeRecoveryRef:
    name: pitr-xiaowen

  bootstrapFrom:
    backupContentType: Logical
    s3:
      bucket: database
      prefix: mariadb-xiaowen/logical
      endpoint: minio.storage.svc.cluster.local:443
      accessKeyIdSecretKeyRef:
        name: mariadb-xiaowen
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-xiaowen
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: homelab-bundle
          key: ca.crt

  # bootstrapFrom:
  #   backupContentType: Physical
  #   s3:
  #     bucket: database
  #     prefix: mariadb-xiaowen/physical
  #     endpoint: minio.storage.svc.cluster.local:443
  #     accessKeyIdSecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: homelab-bundle
  #         key: ca.crt

  # bootstrapFrom:
  #   volumeSnapshotRef:
  #     name: physicalbackup-xiaowen-snap-20250617104042 

  # bootstrapFrom:
  #   pointInTimeRecoveryRef:
  #     name: pitr-xiaowen
  #   targetRecoveryTime: 2026-02-20T18:00:04Z
  #   stagingStorage:
  #     persistentVolumeClaim:
  #       resources:
  #         requests:
  #           storage: 10Gi
  #       accessModes:
  #         - ReadWriteOnce
  #   restoreJob:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         memory: 1Gi
  #   logLevel: debug

  storage:
    size: 10Gi
    storageClassName: topolvm

  tls:
    enabled: true
    required: false
    serverCertIssuerRef:
      name: homelab
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: homelab
      kind: ClusterIssuer

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast
    autoUpdateDataPlane: true

  suspend: false

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1600MB
    slow_query_log
    slow_query_log_file=mariadb-slow.log
    max_binlog_size=64M

  livenessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  startupProbe:
    failureThreshold: 30
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  nodeSelector:
    node.mmontes.io/type: compute-large

  affinity:
    antiAffinityEnabled: true

  podDisruptionBudget:
    maxUnavailable: 66%

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: pb-xiaowen-tpl
spec:
  mariaDbRef:
    name: mariadb-xiaowen
    waitForIt: false
  schedule:
    suspend: true
  maxRetention: 5m
  storage:
    s3:
      bucket: database
      prefix: mariadb-xiaowen/physical/bootstrap
      endpoint: minio.storage.svc.cluster.local:443
      accessKeyIdSecretKeyRef:
        name: mariadb-xiaowen
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-xiaowen
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: homelab-bundle
          key: ca.crt
  target: PreferReplica
  timeout: 1h
  podAffinity: true
  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  successfulJobsHistoryLimit: 2