apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-xiaowen-from-backup
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
    generate: false

  username: xiaowen
  passwordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
  database: photoprism

  image: mariadb:11.4.5

  replicas: 3

  maxScaleRef:
    name: maxscale-xiaowen

  galera:
    enabled: true
    recovery:
      enabled: true
      clusterHealthyTimeout: 1m

  bootstrapFrom:
    backupRef:
      name: physicalbackup-xiaowen
      kind: PhysicalBackup

  # bootstrapFrom:
  #   volume:
  #     nfs:
  #       server: 10.0.0.50
  #       path: /volume1/photoprism/xiaowen/physicalbackup
  #   backupContentType: Physical
  #   restoreJob:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         memory: 1Gi

  # bootstrapFrom:
  #   backupRef:
  #     name: physicalbackup-xiaowen-snap
  #     kind: PhysicalBackup

  # bootstrapFrom:
  #   volumeSnapshotRef:
  #     name: physicalbackup-xiaowen-snap-20250617104042 

  storage:
    size: 10Gi
    storageClassName: rook-ceph

  tls:
    enabled: true
    required: false
    galeraSSTEnabled: true
    serverCertIssuerRef:
      name: homelab
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: homelab
      kind: ClusterIssuer

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast
    # autoUpdateDataPlane: true

  suspend: false

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=700MB
    slow_query_log
    slow_query_log_file=mariadb-slow.log

  livenessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  startupProbe:
    failureThreshold: 30
    periodSeconds: 15
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi

  nodeSelector:
    node.mmontes.io/type: compute

  affinity:
    antiAffinityEnabled: true

  podDisruptionBudget:
    maxUnavailable: 66%