apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-xiaowen
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
    generate: false

  username: xiaowen
  passwordSecretKeyRef:
    name: mariadb-xiaowen
    key: password
  database: photoprism

  image: mariadb:11.8.5

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        storageClassName: topolvm
        resources:
          requests:
            storage: 100Mi
        accessModes:
          - ReadWriteOnce

  # bootstrapFrom:
  #   backupContentType: Logical
  #   s3:
  #     bucket: database
  #     prefix: mariadb-xiaowen/logical
  #     endpoint: minio.storage.svc.cluster.local:443
  #     accessKeyIdSecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: homelab-bundle
  #         key: ca.crt

  # bootstrapFrom:
  #   backupContentType: Physical
  #   s3:
  #     bucket: database
  #     prefix: mariadb-xiaowen/physical
  #     endpoint: minio.storage.svc.cluster.local:443
  #     accessKeyIdSecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: mariadb-xiaowen
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: homelab-bundle
  #         key: ca.crt

  # bootstrapFrom:
  #   volumeSnapshotRef:
  #     name: physicalbackup-xiaowen-snap-20250617104042 

  storage:
    size: 10Gi
    storageClassName: topolvm

  tls:
    enabled: true
    required: false
    galeraSSTEnabled: true
    serverCertIssuerRef:
      name: homelab
      kind: ClusterIssuer
    clientCertIssuerRef:
      name: homelab
      kind: ClusterIssuer

  metrics:
    enabled: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast
    autoUpdateDataPlane: true

  suspend: false

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1600MB
    slow_query_log
    slow_query_log_file=mariadb-slow.log

  livenessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  readinessProbe:
    periodSeconds: 15
    timeoutSeconds: 5

  startupProbe:
    failureThreshold: 30
    periodSeconds: 20
    timeoutSeconds: 5

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi

  tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-large

  nodeSelector:
    node.mmontes.io/type: compute-large

  affinity:
    antiAffinityEnabled: true

  podDisruptionBudget:
    maxUnavailable: 66%