apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-xiaowen
spec:
  mariaDbRef:
    name: mariadb-xiaowen

  config:
    volumeClaimTemplate:
      storageClassName: rook-ceph
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: true
    adminUsername: xiaowen
    adminPasswordSecretKeyRef:
      name: mariadb-xiaowen
      key: password

  metrics:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 128Mi

  nodeSelector:
    node.mmontes.io/type: compute