apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-xiaowen
spec:
  mariaDbRef:
    name: mariadb-xiaowen

  admin:
    port: 8989
    guiEnabled: true

  auth:
    generate: true
    adminUsername: xiaowen
    adminPasswordSecretKeyRef:
      name: mariadb-xiaowen
      key: password

  metrics:
    enabled: true

  priorityClassName: system-node-critical

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 128Mi

  nodeSelector:
    node.mmontes.io/type: compute