apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: physicalbackup-xiaowen
spec:
  mariaDbRef:
    name: mariadb-xiaowen
  schedule:
    cron: "0 10 * * *"
    suspend: false
    immediate: true
  compression: bzip2
  maxRetention: 730h # 1 month
  storage:
    volume:
      nfs:
        server: 10.0.0.50
        path: /volume1/photoprism/xiaowen/physicalbackup
  timeout: 1h
  podAffinity: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi