apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-xiaowen-snap
spec:
  mariaDbRef:
    name: mariadb-xiaowen
  schedule:
    cron: "30 23 * * *"
    suspend: false
    immediate: true
  maxRetention: 168h # 7 days
  storage:
    volumeSnapshot:
      volumeSnapshotClassName: topolvm
  timeout: 1h