apiVersion: k8s.mariadb.com/v1alpha1
kind: PointInTimeRecovery
metadata:
  name: pitr-xiaowen
spec:
  physicalBackupRef:
    name: physicalbackup-xiaowen
  storage:
    s3:
      bucket: database
      prefix: mariadb-xiaowen/binlogs
      endpoint: seaweedfs-s3.storage.svc.cluster.local:8333
      accessKeyIdSecretKeyRef:
        name: mariadb-xiaowen
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: mariadb-xiaowen
        key: secret-access-key
  compression: bzip2
  archiveTimeout: 1h
  strictMode: true