apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism-mmontes
spec:
  releaseName: photoprism-mmontes
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.12.0"
  interval: 5m
  values:
    image:
      repository: photoprism/photoprism
      tag: "251130"
      pullPolicy: IfNotPresent

    env:
      PHOTOPRISM_AUTH: true
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: info
      PHOTOPRISM_READONLY: true
      PHOTOPRISM_SITE_AUTHOR: "Martin Montes"
      PHOTOPRISM_SITE_CAPTION: "Media"
      PHOTOPRISM_SITE_DESCRIPTION: "Media Center"
      PHOTOPRISM_BACKUP_DATABASE: false
      PHOTOPRISM_INDEX_SCHEDULE: "0 */3 * * *"

    secretRef:
      name: photoprism-mmontes

    persistence:
      enabled: true

      nas: &nas 10.0.0.50

      volumes:
        - name: originals
          nfs:
            server: *nas
            path: /volume1/homes/mmontes
            readOnly: true
        - name: import
          nfs:
            server: *nas
            path: /volume1/photoprism/mmontes/import
            readOnly: true
        - name: storage
          persistentVolumeClaim:
            claimName: photoprism-mmontes

      volumeMounts:
        - name: originals
          mountPath: /photoprism/originals
          readOnly: true
        - name: import
          mountPath: /photoprism/import
          readOnly: true
        - name: storage
          mountPath: /photoprism/storage

    database:
      driver: mysql
      dsnSecretKeyRef:
        name: connection-mmontes
        key: dsn

    batch:
      enabled: true
      jobs:
        - name: faces
          cron: "* */3 * * *"
          suspend: true
          command:
            - photoprism
          args:
            - faces
            - index
        - name: vision-labels
          cron: "*/5 * * * *"
          suspend: true
          command:
            - photoprism
          args:
            - vision
            - run
            - -m
            - labels
            - --count
            - 1
            - --force
        - name: vision-caption
          cron: "*/5 * * * *"
          suspend: true
          command:
            - photoprism
          args:
            - vision
            - run
            - -m
            - caption
            - --count
            - 1
            - --force
      resources:
        requests:
          cpu: 4
          memory: 4Gi
        limits:
          memory: 4Gi
      tolerations:
      - effect: NoSchedule
        key: node.mmontes.io/type
        value: compute-xlarge
      nodeSelector:
        node.mmontes.io/type: compute-xlarge

    vision:
      enabled: true
      mountPath: /photoprism/storage/config/vision.yml
      subPath: vision.yml
      config: |
        Models:
        - Type: labels
          Model: gemma3:4b
          Engine: ollama
          Run: manual
          Service:
            Uri: http://ollama.ai.svc.cluster.local:11434/api/generate
        - Type: caption
          Model: gemma3:4b
          Engine: ollama
          Run: manual
          Prompt: >
            Create a caption with exactly one sentence in the active voice that
            describes the main visual content. Begin with the main subject and
            clear action. Avoid text formatting, meta-language, and filler words.
          Service:
            Uri: http://ollama.ai.svc.cluster.local:11434/api/generate

    videoTranscoding:
      enabled: false

    service:
      type: ClusterIP

    httpRoute:
      enabled: true
      host: media.mmontes-internal.duckdns.org
      gatewayRef:
        name: traefik-internal
        namespace: networking

    resources:
      requests:
        cpu: 4
        memory: 4Gi
      limits:
        memory: 4Gi

    tolerations:
    - effect: NoSchedule
      key: node.mmontes.io/type
      value: compute-xlarge

    nodeSelector:
      node.mmontes.io/type: compute-xlarge


