apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - sealedsecret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: photoprism-mmontes
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
