apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: photoprism-mmontes
  namespace: media
spec:
  encryptedData:
    PHOTOPRISM_ADMIN_PASSWORD: AgCcOFrt+ayokvXHY04QypfWfxKFlZYQ4QBb6L7IQazBxbj3JmF/5yFaXAEEhH/B8fLiaxmkgoz460gV0KAT+WFZiJm47QtfogoxI/yUZ+Cb01CIflycih1sX+mYpVUTRRPp6OFphqqs525ODmhrAKC5gkJN2G3FzzepzaAK0TFtnCnw0QQ3gxMpXEJSi2SZhvEJa4jF0TOjf7QlBoBpCePNrJbFNcAdpDpaVr4YM99E3L1q27oWGIg+L/wLK9gLCp1BIV3pC5aeizmMn2CC2EV9wJrWeUHsBcGTRltacB4e9/j8zCuNNTTiS+NSlUbXBJZYuLzeQli9Fp0u/sz8CB50H4wF+x2Lstt+LbbVpO5g34gOnQvDch4Dip7RGuYRwaYzC8XAuanrSvNzyIkZnRZnsRQnr+29t2a2U6a1WD5BlyIiJqWRAngezmpej/3muxDdinmLzG9DNzUcl21w8ZsWXVwKqqECSjiRlI5idOu3cF0+yb4je150FtvRgR73iquQOFttHZDNKo5OwQ8yTSkacdtY/m8rPAZl65hPoYUYnn2m3tsI1pjHqZnD6v8NWRReofs0WNmg36+94TjRTjfxd1f9OuqSgM8EL6YsROgmz3E74OC6JcD5xzWC/wBwnsBWGi4gEuJWJB5qQ1Oqig5AR9l+GWfhXWgJcItwfiyWT7t2VY1kxT9ChsnUQHdoPjM6r4h2PRyhyDjOuPc+k4ybaexc+w==
  template:
    metadata:
      creationTimestamp: null
      name: photoprism-mmontes
      namespace: media
