apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: photoprism-mmontes
spec:
  sourcePVC: photoprism-mmontes
  trigger:
    schedule: "0 1 * * *"
    # manual: mmontes-4
  restic:
    repository: restic-mmontes
    retain:
      daily: 7
    pruneIntervalDays: 14
    unlock: mmontes-1
    # Direct method is required to inherit tolerations from Pod.
    copyMethod: Direct
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
