apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: photoprism-mmontes
spec:
  trigger:
    manual: mmontes-2
  restic:
    repository: restic-mmontes
    destinationPVC: photoprism-mmontes
    # Direct method is required to inherit tolerations from Pod.
    copyMethod: Direct
    moverResources:
      requests:
        cpu: 1
        memory: 300Mi
      limits:
        memory: 4Gi
    cacheCapacity: 10Gi
    cacheStorageClassName: topolvm
    cacheAccessModes:
      - ReadWriteOnce
    customCA:
      secretName: homelab-bundle
      key: ca.crt
