image:
  repository: photoprism/photoprism
  tag: "220302-bullseye"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "mmontes"
  PHOTOPRISM_SITE_CAPTION: "mmontes media center"
  PHOTOPRISM_SITE_DESCRIPTION: "mmontes media center"

secretRef:
  name: photoprism-mmontes

persistence:
  enabled: true

  nas: &nas nas.local
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/mmontes
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/import
    - name: storage
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  host: photoprism-mmontes-mariadb:3306

sync:
  enabled: true
  cron: "0 2 * * *"
  resources:
    requests:
      memory: 300Mi
      cpu: 300m
    limits:
      memory: 1.5Gi
      cpu: 700m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
              - key: node.mmontes.io/type
                operator: In
                values:
                  - compute

service:
  type: ClusterIP
  port: 80

ingressRoute:
  enabled: true
  host: media.mmontes-dev.duckdns.org
  entryPoints:
    - websecure

resources:
  requests:
    memory: 300Mi
    cpu: 300m
  limits:
    memory: 1.5Gi
    cpu: 700m

nodeSelector:
  node.mmontes.io/type: compute
