image:
  repository: photoprism/photoprism
  tag: "240915"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "Martin Montes"
  PHOTOPRISM_SITE_CAPTION: "Media"
  PHOTOPRISM_SITE_DESCRIPTION: "Media Center"
  PHOTOPRISM_BACKUP_DATABASE: false
  PHOTOPRISM_INDEX_SCHEDULE: ""

secretRef:
  name: photoprism-mmontes

persistence:
  enabled: true

  nas: &nas 10.0.0.50
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/mmontes
        readOnly: true
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/import
        readOnly: true
    - name: backup
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/storage
    - name: storage
      persistentVolumeClaim:
        claimName: photoprism-mmontes

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
      readOnly: true
    - name: import
      mountPath: *importPath
      readOnly: true
    - name: storage
      mountPath: *storagePath
    - name: backup
      mountPath: /backup

database:
  driver: mysql
  dsnSecretKeyRef:
    name: connection-mmontes
    key: dsn

sync:
  enabled: true
  cron: "0 11,13,15,17,19,21,23 * * *"
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 2Gi

videoTranscoding:
  enabled: false

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  host: media.mmontes-internal.duckdns.org
  gatewayRef:
    name: traefik-internal
    namespace: networking

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    memory: 2Gi

nodeSelector:
  node.mmontes.io/type: compute