image:
  repository: photoprism/photoprism
  tag: "240531"
  pullPolicy: IfNotPresent

env:
  PHOTOPRISM_AUTH: true
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: debug
  PHOTOPRISM_READONLY: true
  PHOTOPRISM_SITE_AUTHOR: "mmontes"
  PHOTOPRISM_SITE_CAPTION: "mmontes media center"
  PHOTOPRISM_SITE_DESCRIPTION: "mmontes media center"
  PHOTOPRISM_BACKUP_DATABASE: false
  PHOTOPRISM_INDEX_SCHEDULE: ""
  PHOTOPRISM_FFMPEG_ENCODER: "raspberry"
  PHOTOPRISM_FFMPEG_BUFFERS: "64"

secretRef:
  name: photoprism-mmontes

persistence:
  enabled: true

  nas: &nas 10.0.0.50
  originalsPath: &originalsPath /photoprism/originals
  importPath: &importPath /photoprism/import
  storagePath: &storagePath /photoprism/storage

  volumes:
    - name: originals
      nfs:
        server: *nas
        path: /volume1/homes/mmontes
        readOnly: true
    - name: import
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/import
    - name: storage
      nfs:
        server: *nas
        path: /volume1/photoprism/mmontes/storage

  volumeMounts:
    - name: originals
      mountPath: *originalsPath
      readOnly: true
    - name: import
      mountPath: *importPath
    - name: storage
      mountPath: *storagePath

database:
  driver: mysql
  dsnSecretKeyRef:
    name: connection-mmontes
    key: dsn

sync:
  enabled: true
  cron: "0 */3 * * *"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      memory: 2Gi

videoTranscoding:
  enabled: true
  device: "/dev/video20"

service:
  type: ClusterIP
  port: 80

httpRoute:
  enabled: true
  host: media.mmontes-internal.duckdns.org
  gatewayRef:
    name: traefik-internal
    namespace: networking

resources:
  requests:
    cpu: 1
    memory: 1Gi

nodeSelector:
  node.mmontes.io/type: compute